MYSQL_HOST = 'localhost'
MYSQL_USER = 'user_name'
MYSQL_PASW = 'user_pass'
MYSQL_DATABASE = 'insales'
LOGGING = True
LOCAL_MODE = 1
LOG_FILE = 'log.txt'
TEST_MODE = True
LOGIN = 'login100500'
PASSW = 'pass1qa'
# URL = 'localhost:5577'
URL = 'http://profit.i-bots.ru'