avito_cols = {
    'common': (
        'Id',
        'Address',
        'Category',
        'Title',
        'ContactPhone',
        'Description',
        'GoodsType',
        'AdType',
        'ProductType',
        'SparePartType',
        'TypeId',
        'Brand',
        'Model',
        'TireSectionWidth',
        'TireAspectRatio',
        'TireType',
        'Quantity',
        'Voltage',
        'Capacity',
        'DCL',
        'Polarity',
        'Length',
        'Width',
        'Height',
        'OEM',
        'RimWidth',
        'RimDiameter',
        'RimOffset',
        'RimBolts',
        'RimBoltsDiameter',
        'RimDIA',
        'RimType',
        'Condition',
        'Price',
        'ImageUrls'
    ),
    'tires': [
        'Id',
        'Address',
        'Category',
        'Title',
        'ContactPhone',
        'Description',
        'GoodsType',
        'AdType',
        'ProductType',
        'SparePartType',
        'TypeId',
        'Brand',
        'Model',
        'OEM',
        'TireSectionWidth',
        'RimDiameter',
        'TireAspectRatio',
        'TireType',
        'Quantity',
        'Condition',
        'Price',
        'ImageUrls'
    ],
    'akk': [
        'Id',
        'Address',
        'Category',
        'Title',
        'Description',
        'GoodsType',
        'AdType',
        'ProductType',
        'SparePartType',
        'Voltage',
        'Capacity',
        'DCL',
        'Polarity',
        'Length',
        'Width',
        'Height',
        'Condition',
        'Brand',
        'OEM',
        'Price',
        'ImageUrls'
    ],
    'wheels': [
        'Id',
        'Address',
        'Category',
        'Title',
        'Description',
        'GoodsType',
        'AdType',
        'ProductType',
        'RimWidth',
        'RimDiameter',
        'RimOffset',
        'RimBolts',
        'RimBoltsDiameter',
        'RimDIA',
        'RimType',
        'Condition',
        'Price',
        'ImageUrls'
    ]
}

goods = {
    'csv': {
        'tires': 'https://3431.ru/system/unload_prices/12/tires.csv',
        'wheels': 'https://3431.ru/system/unload_prices/14/wheelavito.csv',
        'akk': 'https://3431.ru/system/unload_prices/11/akk.csv'
    },
    'xml': {
        'tires': 'https://3431.ru/system/unload_prices/12/avito.xml',
        'wheels': 'https://3431.ru/system/unload_prices/14/avito.xml',
        'akk': 'https://3431.ru/system/unload_prices/11/avito.xml'
    }
}

checks = {
    'brands': 'https://www.avito.ru/web/1/autoload/user-docs/category/67016/field/110431/values-xml',
    'models': 'https://autoload.avito.ru/format/tyres_make.xml'
}

yandex = {
    'xml': 'https://3431.ru/system/unload_prices/3/yandex_market.xml',
    'csv': 'https://3431.ru/system/unload_prices/3/yandexneo.csv'
}

dop = {
    'xml': {
        'tires': 'https://3431.ru/system/unload_prices/16/yandex_market.xml',
        'wheels': 'https://3431.ru/system/unload_prices/15/yandex_market.xml',
        'akk': 'https://3431.ru/system/unload_prices/11/avito.xml'
    },
    'csv': {
        'tires': 'https://3431.ru/system/unload_prices/15/diskiyam.csv',
        'wheels': 'https://3431.ru/system/unload_prices/15/diskiyam.csv',
        'akk': 'https://3431.ru/system/unload_prices/13/akkyam.csv'
    }
}

params_names_for_check = {
    'akk': ('length', 'width', 'height', 'dcl', 'voltage', 'capacity'),
    'wheels': ('rimwidth', 'rimdiameter', 'rimoffset', 'rimbolts', 'rimboltsdiameter', 'rimdia'),
    'tires': ('tiresecwidth', 'tirerimdiameter', 'tireaspectratio')
}

tires_rim_diameter = [
    '4',
    '5',
    '5.5',
    '6',
    '6.5',
    '6.7',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '12C',
    '13',
    '13C',
    '13.5',
    '14',
    '14C',
    '14.5',
    '15',
    '15.3',
    '15.5',
    '15C',
    '16',
    '16.1',
    '16.5',
    '16C',
    '17',
    '17C',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '24.5',
    '25',
    '26',
    '26.5',
    '27',
    '28',
    '29',
    '30',
    '30.5',
    '31',
    '32',
    '33',
    '34',
    '35',
    '36',
    '38',
    '40',
    '42',
    '44',
    '45',
    '46',
    '48',
    '50',
    '55'
]

params_checker = {
    'voltage': {
        '4', '6', '12', '18', '24', '48',
    },
    'capacity': {
        '1.2',
        '2.5',
        '5',
        '10',
        '15',
        '20',
        '25',
        '30',
        '35',
        '40',
        '45',
        '50',
        '53',
        '55',
        '58',
        '60',
        '61',
        '62',
        '63',
        '64',
        '65',
        '66',
        '68',
        '70',
        '72',
        '74',
        '75',
        '77',
        '78',
        '80',
        '85',
        '90',
        '95',
        '100',
        '105',
        '110',
        '115',
        '120',
        '125',
        '128',
        '130',
        '132',
        '135',
        '140',
        '145',
        '150',
        '155',
        '160',
        '165',
        '170',
        '175',
        '180',
        '185',
        '190',
        '195',
        '200',
        '205',
        '210',
        '215',
        '220',
        '225',
        '230',
        '235',
        '240',
    },
    'dcl': {
        '12',
        '45',
        '65',
        '100',
        '110',
        '120',
        '130',
        '140',
        '150',
        '160',
        '170',
        '180',
        '190',
        '200',
        '210',
        '220',
        '230',
        '240',
        '250',
        '260',
        '270',
        '280',
        '290',
        '300',
        '310',
        '320',
        '330',
        '340',
        '350',
        '360',
        '370',
        '380',
        '390',
        '400',
        '410',
        '420',
        '430',
        '440',
        '450',
        '460',
        '470',
        '480',
        '490',
        '500',
        '510',
        '520',
        '530',
        '540',
        '550',
        '560',
        '570',
        '580',
        '590',
        '600',
        '610',
        '620',
        '630',
        '640',
        '650',
        '660',
        '670',
        '680',
        '690',
        '700',
        '710',
        '720',
        '730',
        '740',
        '750',
        '760',
        '770',
        '780',
        '790',
        '800',
        '810',
        '820',
        '830',
        '840',
        '850',
        '860',
        '870',
        '880',
        '890',
        '900',
        '910',
        '920',
        '930',
        '940',
        '950',
        '960',
        '970',
        '980',
        '990',
        '1000',
        '1010',
        '1020',
        '1030',
        '1040',
        '1050',
        '1060',
        '1070',
        '1080',
        '1090',
        '1100',
        '1110',
        '1120',
        '1130',
        '1140',
        '1150',
        '1160',
        '1170',
        '1180',
        '1190',
        '1200',
        '1210',
        '1220',
        '1230',
        '1240',
        '1250',
        '1260',
        '1270',
        '1280',
        '1290',
        '1300',
        '1310',
        '1320',
        '1330',
        '1340',
        '1350',
        '1360',
        '1370',
        '1380',
        '1390',
        '1400',
        '1410',
        '1420',
        '1430',
        '1440',
        '1450',
        '1460',
        '1470',
        '1480',
        '1490',
        '1500',
        '1510',
        '1520',
        '1530',
        '1540',
        '1550',
        '1650',
    },
    'length': {
        '98',
        '113',
        '114',
        '120',
        '133',
        '134',
        '135',
        '150',
        '151',
        '160',
        '168',
        '175',
        '181',
        '186',
        '187',
        '205',
        '207',
        '229',
        '230',
        '232',
        '235',
        '237',
        '238',
        '240',
        '242',
        '254',
        '257',
        '260',
        '261',
        '266',
        '276',
        '277',
        '278',
        '302',
        '305',
        '306',
        '315',
        '330',
        '352',
        '353',
        '390',
        '393',
        '394',
        '425',
        '501',
        '513',
        '518',
    },
    'width': {
        '38',
        '43',
        '61',
        '62',
        '66',
        '70',
        '71',
        '73',
        '75',
        '80',
        '86',
        '87',
        '88',
        '89',
        '90',
        '100',
        '127',
        '129',
        '132',
        '160',
        '169',
        '170',
        '172',
        '173',
        '175',
        '180',
        '189',
        '223',
        '240',
        '269',
        '276',
    },
    'height': {
        '57',
        '85',
        '86',
        '92',
        '93',
        '94',
        '105',
        '110',
        '129',
        '130',
        '131',
        '138',
        '145',
        '147',
        '155',
        '159',
        '160',
        '161',
        '164',
        '165',
        '175',
        '176',
        '190',
        '192',
        '200',
        '220',
        '222',
        '223',
        '224',
        '225',
        '226',
        '227',
        '240',
        '242',
        '269',
    },
    'rimwidth': {
        '3.5',
        '2.15',
        '4',
        '4.5',
        '5',
        '5.5',
        '6',
        '6.5',
        '6.75',
        '7',
        '7.5',
        '8',
        '8.5',
        '8.25',
        '9',
        '9.5',
        '10',
        '10.5',
        '11',
        '11.5',
        '11.25',
        '11.75',
        '12',
        '12.5',
        '13',
        '14',
        '15',
        '15.7',
        '18',
        '23',
        '25',
    },
    'rimdiameter': {
        '4',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '15.3',
        '16',
        '16.5',
        '17',
        '17.5',
        '18',
        '19',
        '19.5',
        '20',
        '21',
        '22',
        '22.5',
        '23',
        '24',
        '25',
        '26',
        '26.5',
        '27',
        '28',
        '29',
        '30',
        '32',
        '33',
        '34',
        '35',
        '36',
        '38',
        '40',
        '42',
        '45',
        '50',
        '55',
    },
    'rimoffset': {
        '-2',
        '-5',
        '-6',
        '-7',
        '-8',
        '-10',
        '-12',
        '-13',
        '-14',
        '-15',
        '-16',
        '-18',
        '-19',
        '-20',
        '-22',
        '-24',
        '-25',
        '-28',
        '-30',
        '-32',
        '-35',
        '-36',
        '-38',
        '-40',
        '-44',
        '-45',
        '-46',
        '-50',
        '-65',
        '-88',
        '-90',
        '-98',
        '-120',
        '-130',
        '-155',
        '-172',
        '-187',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '23.5',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '31.5',
        '32',
        '33',
        '34',
        '34.5',
        '35',
        '35.5',
        '36',
        '36.5',
        '37',
        '37.5',
        '38',
        '39',
        '39.5',
        '40',
        '40.5',
        '41',
        '41.3',
        '41.5',
        '42',
        '42.5',
        '43',
        '43.5',
        '43.8',
        '44',
        '45',
        '45.5',
        '46',
        '47',
        '47.5',
        '48',
        '48.5',
        '49',
        '49.5',
        '50',
        '50.5',
        '50.8',
        '51',
        '52',
        '52.2',
        '52.5',
        '53',
        '54',
        '55',
        '56',
        '56.4',
        '56.5',
        '57',
        '58',
        '59',
        '60',
        '61',
        '62',
        '62.5',
        '62.6',
        '63',
        '64',
        '65',
        '66',
        '67',
        '68',
        '69',
        '70',
        '75',
        '76',
        '80',
        '83',
        '90',
        '95',
        '100',
        '102',
        '105',
        '105.5',
        '106',
        '107',
        '108',
        '109',
        '109.5',
        '110',
        '111',
        '114',
        '115',
        '116',
        '118',
        '120',
        '123',
        '124',
        '125',
        '126',
        '127',
        '128',
        '129',
        '129,5',
        '130',
        '132',
        '133',
        '134',
        '135',
        '136',
        '138',
        '140',
        '142',
        '143',
        '144',
        '145',
        '145,5',
        '147',
        '148',
        '150',
        '151.4',
        '151.4',
        '152',
        '154',
        '154,4',
        '155',
        '155,5',
        '156',
        '157',
        '160',
        '161',
        '162',
        '163',
        '163,5',
        '164',
        '165',
        '167',
        '168',
        '172',
        '173',
        '174',
        '174.5',
        '174.5',
        '175',
        '177.5',
        '180',
        '185',
        '195',
        '214',
        '215',
        '293',
    },
    'rimbolts': {
        '0',
        '3',
        '4',
        '5',
        '6',
        '8',
        '9',
        '10',
        '11',
        '12',
        '19',
        '24',
    },
    'rimboltsdiameter': {
        '0',
        '98',
        '100',
        '105',
        '108',
        '110',
        '112',
        '114.3',
        '115',
        '118',
        '120',
        '120.6',
        '120.7',
        '120.65',
        '125',
        '127',
        '130',
        '135',
        '137',
        '139',
        '139.1',
        '139.7',
        '140',
        '150',
        '156',
        '160',
        '161',
        '165',
        '165.1',
        '170',
        '180',
        '190',
        '200',
        '205',
        '222.25',
        '225',
        '245',
        '256',
        '275',
        '285.75',
        '286',
        '288',
        '335',
        '425',
        '450',
        '480',
        '500',
        '511',
    },
    'rimdia': {
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '38',
        '40',
        '42',
        '52',
        '52.5',
        '54',
        '54.1',
        '55',
        '56',
        '56.1',
        '56.2',
        '56.5',
        '56.6',
        '56.7',
        '56.62',
        '57',
        '57.06',
        '57.1',
        '57.3',
        '57.12',
        '58',
        '58.1',
        '58.5',
        '58.6',
        '58.7',
        '58.8',
        '59',
        '59.1',
        '60',
        '60.06',
        '60.1',
        '60.2',
        '60.5',
        '60.8',
        '60.15',
        '61.1',
        '61.9',
        '63',
        '63.3',
        '63.4',
        '63.34',
        '63.35',
        '64',
        '64.1',
        '64.3',
        '64.12',
        '65',
        '65.05',
        '65.06',
        '65.1',
        '65.2',
        '66',
        '66.06',
        '66.1',
        '66.2',
        '66.4',
        '66.5',
        '66.6',
        '66.7',
        '66.15',
        '66.45',
        '66.46',
        '66.55',
        '66.56',
        '66.69',
        '67',
        '67.04',
        '67.05',
        '67.06',
        '67.08',
        '67.1',
        '67.2',
        '67.7',
        '67.14',
        '68',
        '69',
        '69.1',
        '70',
        '70.02',
        '70.1',
        '70.2',
        '70.3',
        '70.4',
        '70.5',
        '70.6',
        '70.7',
        '70.27',
        '71',
        '71.1',
        '71.4',
        '71.5',
        '71.6',
        '71.8',
        '71.56',
        '71.58',
        '71.69',
        '72',
        '72.1',
        '72.2',
        '72.3',
        '72.5',
        '72.6',
        '72.7',
        '72.55',
        '72.56',
        '72.62',
        '72.69',
        '73',
        '73.06',
        '73.1',
        '73.2',
        '73.3',
        '73.6',
        '73.8',
        '73.9',
        '74',
        '74.1',
        '74.2',
        '74.5',
        '74.6',
        '75',
        '75.1',
        '76',
        '76.1',
        '76.9',
        '77',
        '77.7',
        '77.8',
        '77.9',
        '77.77',
        '78',
        '78.09',
        '78.1',
        '78.3',
        '79',
        '79.1',
        '79.5',
        '79.6',
        '80',
        '81.5',
        '82',
        '83',
        '83.5',
        '83.7',
        '84',
        '84.1',
        '84.2',
        '86.8',
        '86.9',
        '87',
        '87.1',
        '87.2',
        '89',
        '89.1',
        '89.3',
        '92',
        '92.1',
        '92.3',
        '92.5',
        '93',
        '93.1',
        '95',
        '95.1',
        '95.3',
        '95.4',
        '95.5',
        '95.6',
        '98',
        '98.1',
        '98.5',
        '98.6',
        '100',
        '100.1',
        '100.3',
        '100.5',
        '101',
        '102',
        '104.1',
        '106',
        '106.1',
        '106.2',
        '106.3',
        '106.5',
        '106.6',
        '106.25',
        '107',
        '107.1',
        '107.5',
        '107.6',
        '108',
        '108.1',
        '108.2',
        '108.3',
        '108.4',
        '108.5',
        '108.6',
        '108.7',
        '109',
        '109.5',
        '109.7',
        '109.8',
        '110',
        '110.1',
        '110.2',
        '110.3',
        '110.5',
        '110.6',
        '111',
        '111.2',
        '111.6',
        '111.8',
        '112',
        '112.1',
        '112.2',
        '112.5',
        '113',
        '113.1',
        '114.3',
        '116.1',
        '117',
        '118',
        '120',
        '120.9',
        '122.5',
        '125',
        '125.1',
        '127',
        '130',
        '130.1',
        '131',
        '138.8',
        '139',
        '139.7',
        '141',
        '142.1',
        '150',
        '160',
        '161',
        '163',
        '164',
        '176',
        '202',
        '205',
        '214',
        '220',
        '221',
        '222',
        '230',
        '281',
        '282',
        '371',
        '402',
        '423',
        '431',
        '449',
        '460',
        '472',
    },
    'tiresecwidth': {
        '2.25',
        '3.25',
        '3.75',
        '4',
        '4.00',
        '4.25',
        '5',
        '5.00',
        '5.10',
        '5.40',
        '5.50',
        '5.60',
        '6',
        '6.00',
        '6.5',
        '6.25',
        '6.40',
        '6.50',
        '6.7',
        '6.95',
        '7',
        '7.00',
        '7.5',
        '7.50',
        '8',
        '8.3',
        '8.4',
        '8.5',
        '8.15',
        '8.25',
        '8.40',
        '9',
        '9.00',
        '9.5',
        '10',
        '10.00',
        '10.5',
        '10.8',
        '11',
        '11.00',
        '11.2',
        '11.5',
        '11L',
        '12',
        '12.00',
        '12.4',
        '12.5',
        '13',
        '13.00',
        '13.6',
        '14',
        '14.00',
        '14.5',
        '14.9',
        '14.25',
        '14.75',
        '15',
        '15.00',
        '15.3',
        '15.5',
        '16',
        '16.00',
        '16.5',
        '16.9',
        '16.24',
        '17.5',
        '18',
        '18.00',
        '18.4',
        '18.7',
        '18.8',
        '19.5',
        '20',
        '20.5',
        '20.8',
        '21',
        '21.3',
        '21.5',
        '21.8',
        '21L',
        '22',
        '23',
        '23.1',
        '23.5',
        '23.5L',
        '24',
        '24.0',
        '24.5',
        '25',
        '26',
        '26.5',
        '27',
        '28',
        '28.1',
        '28L',
        '29.5',
        '30',
        '30.5',
        '31',
        '31.5',
        '32',
        '33',
        '35',
        '37',
        '38',
        '40',
        '65',
        '71',
        '75',
        '85',
        '87',
        '95',
        '115',
        '125',
        '130',
        '135',
        '145',
        '150',
        '155',
        '165',
        '175',
        '185',
        '190',
        '195',
        '200',
        '205',
        '215',
        '225',
        '230',
        '235',
        '240',
        '245',
        '255',
        '260',
        '265',
        '270',
        '275',
        '285',
        '295',
        '300',
        '305',
        '315',
        '320',
        '325',
        '335',
        '340',
        '345',
        '355',
        '360',
        '365',
        '370',
        '375',
        '380',
        '385',
        '390',
        '395',
        '400',
        '405',
        '415',
        '420',
        '425',
        '435',
        '440',
        '445',
        '455',
        '460',
        '480',
        '500',
        '520',
        '530',
        '540',
        '550',
        '560',
        '580',
        '600',
        '605',
        '620',
        '650',
        '690',
        '700',
        '710',
        '800',
        '850',
        '900',
        '1025',
        '1050',
        '1065',
        '1100',
        '1200',
        '1220',
        '1280',
        '1300',
        '1500',
        '1600',
        'Другое',
    },
    'tirerimdiameter': {
        '4',
        '5',
        '5.5',
        '6',
        '6.5',
        '6.7',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '12C',
        '13',
        '13C',
        '13.5',
        '14',
        '14C',
        '14.5',
        '15',
        '15.3',
        '15.5',
        '15C',
        '16',
        '16.1',
        '16.5',
        '16C',
        '17',
        '17C',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '24.5',
        '25',
        '26',
        '26.5',
        '27',
        '28',
        '29',
        '30',
        '30.5',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '38',
        '40',
        '42',
        '44',
        '45',
        '46',
        '48',
        '50',
        '55',
        'Другое',
    },
    'tireaspectratio': {
        '4.5',
        '5',
        '6',
        '7',
        '8',
        '8.5',
        '9',
        '9.5',
        '10',
        '10.5',
        '11.5',
        '12.5',
        '13.5',
        '15.5',
        '20',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '32',
        '35',
        '40',
        '45',
        '50',
        '55',
        '60',
        '65',
        '70',
        '75',
        '80',
        '85',
        '90',
        '95',
        '100',
        '105',
        '180',
        '400',
        '420',
        '500',
        '530',
        '600',
        '700',
        '710',
        '720',
        '740',
        'Другое',
    }
}

yam_cols = {
    'main': (
        'name',
        'price', 
        'currencyId', # RUB
        'picture', # нету
        'description', 
        'categoryId', # 207 или хз
        'vendor', 
        'vendorCode', 
        # 'param', 
        'store', # true
        'pickup', # true
        'delivery', # true
        # delivery-options
        # pickup-options
    ),
    'dop': {
        'wheels': (
            'Вид',
            'Вылет (ET), мм',
            'Диаметр обода (D)',
            'Диаметр расположения отверстий',
            'Диаметр центрального отверстия (DIA), мм',
            'Количество крепежных отверстий',
            'Ширина обода (J)'
        ),
        'akk': (
            'Напряжение',
            'Пусковой ток, А',
            'Емкость, А·ч',
            'Полярность',
            # 'Тип автотехники',
            'Длина, мм',
            'Ширина, мм',
            'Высота, мм',
        ),
        'tires': (
            'Высота профиля',
            'Диаметр',
            'Ширина профиля',
            'Сезонность',
            'Шипы'
        )
    }
}

yam_param_checker = {
    'akk': {
        'brand': {
            '#ODИH',
            '1000 Новых Нарядов',
            '777',
            'A-Mega',
            'ABSEL',
            'Absolut',
            'AC/DC*',
            'ACDelco',
            'Acmepower',
            'AD',
            'Afa',
            'AGM',
            'AIRLINE',
            'AJAX',
            'AKBMAX',
            'Akuma',
            'Alarm Force',
            'ALASKA',
            'ALCA',
            'ALFA Battery',
            'Alfi Parts',
            'ALLPOWERS',
            'ALPHA Battery',
            'AlphaLine',
            'Alton',
            'Amazin',
            'AMEGA',
            'American',
            'AmperIn',
            'Anysmart',
            'Apriori',
            'ARC',
            'ArtNoMore',
            'Asian Horse',
            'ASIWO',
            'ASP MENSAN',
            'ASTROhim',
            'at autoteile',
            'ATAKA',
            'ATE',
            'Atlas',
            'ATLASBX',
            'Atom',
            'ATOMAN',
            'AURORA',
            'AutoJet',
            'AutoPart',
            'Autopart RED',
            'Autopower',
            'AUTOPROFI',
            'AUTOTEC',
            'AUTOVIRAZH',
            'AVS',
            'AvtoSil',
            'AWM',
            'Axiom',
            'Azimut',
            'B.B. Battery',
            'Babiators',
            'Balever',
            'Banner',
            'Baren',
            'BARS',
            'Baseus',
            'Batt Kraft',
            'BattARSENAL',
            'Bayern Batterie',
            'BeeZmoto',
            'Berga',
            'BESF1TS',
            'Best Dinner',
            'Beyerdynamic',
            'BIG FIGHTER',
            'BILSTEIN',
            'Black',
            'BLACK ICE',
            'Blizzaro',
            'BM NRG',
            'BMW',
            'BOLK',
            'Borg',
            'BOSCH',
            'Bosch',
            'BOST',
            'BOXBOT',
            'BRAND',
            'BS Battery',
            'BURAN',
            'Bushido',
            'BYD',
            'Camel',
            'Camelion',
            'Cameron Sino',
            'Cana',
            'cargen',
            'CARVILLE RACING',
            'Casil',
            'CASP',
            'Cene',
            'Centra',
            'Challenger',
            'CHAMPION',
            'CHAMPION PILOT DRIVE',
            'CHILWEE',
            'Chopper',
            'CITYCOCO',
            'CityUp',
            'Cobat energy',
            'Cocoa honey',
            'COJALI',
            'CONTITECH',
            'Cooler Master',
            'COUGAR',
            'Crafter',
            'CRC',
            'CROM',
            'CS20',
            'CSB',
            'CyberPower',
            'Cyma',
            'Daewoo',
            'DECUS',
            'Deka',
            'Delkor',
            'DELTA',
            'DELTA',
            'DELTA Battery',
            'Delta Electronics',
            'DENSO',
            'Deqst',
            'Deta',
            'DIMAXX',
            'Ding Tai Battery',
            'DKC',
            'DMEGC',
            'Docker',
            'Doglike',
            'Dominator',
            'DPM',
            'DT spare parts',
            'Dualtron',
            'DUGLAS',
            'DUOSIDA',
            'Duracell',
            'DVH',
            'Dyno Europe',
            'E-LAB',
            'E-Nex',
            'EAS',
            'EATON',
            'ECOMAX',
            'ECOSTART',
            'Edcon',
            'Effekta',
            'EFREMOV',
            'EKOAKB.ru',
            'Elhim-Iskra',
            'Eltreco',
            'ENEOS',
            'Energizer',
            'Energy',
            'Energy Box',
            'Energy Technology',
            'ENEUS',
            'ENRUN',
            'ERA',
            'ERGINEX',
            'Estro',
            'Etalon battery',
            'eTrend',
            'Europart',
            'Eurostart',
            'EVEREST Energy',
            'Exclusive',
            'EXICE',
            'Exide',
            'Extra Start',
            'Eсostart',
            'FAW',
            'FB',
            'Feon',
            'FEYT',
            'Fiamm',
            'Fire Bull',
            'FireBall',
            'FKVJP',
            'FORCE',
            'Ford',
            'FORSAGE',
            'Forse',
            'Forte',
            'Fortex',
            'Forward',
            'FQ',
            'FREIGHTLINER',
            'Fubag',
            'FULBAT',
            'Furukawa Battery',
            'FXA',
            'GENERAL MOTORS',
            'General Security',
            'General Technologies',
            'GIGAWATT',
            'Gillette Magico',
            'GINNES',
            'GIVER',
            'GLASER',
            'Global Battery',
            'GLOBATT',
            'Godzima',
            'Golden Horse',
            'GP',
            'Graffit',
            'Graisburg',
            'GREENLER',
            'Greenway',
            'Greenworks',
            'GRIZLY',
            'GS',
            'GS Yuasa',
            'GWS Energy',
            'Hagen Batterien',
            'Haldex',
            'Hankook',
            'Haval',
            'Hawker',
            'HD-PARTS',
            'HEMEN',
            'Hi-Gear',
            'HILLPORT',
            'Horse',
            'HUGEL',
            'Human Friends',
            'Husqvarna',
            'Huter',
            'HYUNDAI',
            'Hyundai',
            'Hyundai/KIA',
            'IMPROVE',
            'Inci Aku',
            'Intact',
            'INTREPID',
            'Involight',
            'ISKRA ENERGY',
            'ISTA',
            'Jaguar',
            'Jetson',
            'Jiangxi',
            'Johnson Controls',
            'Joker',
            'JONNESWAY',
            'Jorden',
            'KAGE',
            'Kainar',
            'Kamukamu',
            'KANAVANO',
            'Kangaroo',
            'KARCHER',
            'KARHU',
            'KBK',
            'KELENATE',
            'KERRY',
            'KING TONY',
            'KirMaxx',
            'Klema',
            'Koba',
            'KOBE',
            'KOITO',
            'KONNWEI',
            'Korting',
            'Kraft',
            'KUCH',
            'KUGOO',
            'LANDPORT',
            'LECAR',
            'Lenmar',
            'Lentel',
            'Leoch',
            'Lexman',
            'LEXUS',
            'LG',
            'Lights of Nord',
            'LiitoKala',
            'Lipai',
            'LitJet',
            'LORD',
            'Luxeon',
            'Lynx',
            'LYNXauto',
            'Makita',
            'MAN',
            'Master Road',
            'Maxinter',
            'Mazda',
            'Medalist',
            'Mega Batt',
            'MegaStart',
            'Messer',
            'METACO',
            'MG Motor',
            'Mighty Seven',
            'Minamoto',
            'MINI',
            'Minn Kota',
            'MIWI',
            'MOBIS',
            'MOLL',
            'Moll',
            'MONBAT',
            'Moratti',
            'MOTRIO',
            'Multi Tec',
            'Mutlu',
            'NAKAMOTO',
            'Neovolt',
            'NEW GALAXY',
            'New-AKB',
            'Nextorch',
            'NG',
            'NGK',
            'Nilfisk',
            'Njoy',
            'NO NAME',
            'NOK Group',
            'Nokia',
            'Nomoy Pet',
            'Noname',
            'Nord Star',
            'Nordix',
            'Nordlinger',
            'Normal',
            'Nova Bright',
            'NOVOL',
            'NSP',
            'Oasis',
            'Oberon',
            'Odyssey',
            'OILRIGHT',
            'Omax Genuine',
            'ON',
            'ONYARBI',
            'Optima',
            'Optima Batteries',
            'Original',
            'Ortonica',
            'OSRAM',
            'Oursun',
            'OUTDO',
            'P.I.T.',
            'pacol',
            'Palma',
            'Panasonic',
            'PATRON',
            'PERION',
            'PERMATEX',
            'Pitatel',
            'PLATIN',
            'PORSCHE',
            'POWER',
            'POWER SHARK',
            'POWERMAQ',
            'President',
            'PRIME MOTO',
            'PRO START',
            'Prometheus Energy',
            'PSA Peugeot Citroen',
            'Pulsar',
            'Puma',
            'Racer',
            'RAYFORT',
            'RDrive',
            'REACTOR',
            'RED',
            'RED ENERGY',
            'redBTR',
            'Redskin',
            'RedVerg',
            'reinWell',
            'Relato',
            'Renault',
            'RENAULT TRUCKS',
            'REXANT',
            'Ridicon',
            'Ridzel',
            'RLINESportNutrition',
            'ROCKFORCE',
            'Roco',
            'ROKODIL',
            'Root Note',
            'Rostar',
            'ROX Standard',
            'RUSEFF',
            'Rutrike',
            'S&K',
            'Sailing',
            'SALUT',
            'Sanfox',
            'Santak',
            'SATA',
            'SEBANG',
            'Security Force',
            'SHELL',
            'Shenzhen Toys',
            'sia',
            'SIAP',
            'SIBBEAR',
            'Siltech',
            'Sino Power',
            'SJRC',
            'Skybox',
            'Skyrich',
            'SKYWAY',
            'Sokkia',
            'Sokol',
            'Solar',
            'Solite',
            'Sombor',
            'Sonnenschein',
            'Sony',
            'SOONWELL',
            'Soshine',
            'Spark',
            'SpeedMate',
            'Stalwart',
            'Stark',
            'STARKSBAT',
            'START.Bat',
            'Starta',
            'STARTVOLT',
            'STIHL',
            'Stinger',
            'Stonelock',
            'STORM',
            'StP',
            'STVOL',
            'Sunways',
            'Super Nova',
            'Supreme',
            'SUZUMU',
            'SWAT',
            'Switch',
            'Sznajder',
            'TAB',
            'Talvi',
            'TangDe',
            'Taxxon',
            'TECHNIK-MESSER',
            'Technocom',
            'TEH',
            'Telwin',
            'Tenax',
            'Tensy',
            'TEPLOCOM',
            'TES',
            'TESLA',
            'TESLA',
            'Tesla',
            'Tesla Technics',
            'test',
            'THERMOCASE',
            'Thomas',
            'Thorvik',
            'Tiger',
            'TIMBERG',
            'TITAN',
            'Titbit',
            'TMMP',
            'Tokler',
            'TOP AUTO',
            'Topbat',
            'TopCover',
            'Topla',
            'TOR',
            'Tornado',
            'Torso',
            'TOTACHI',
            'TRIGGER',
            'Trojan',
            'TUBOR',
            'Tudor',
            'Tungstone',
            'Turbo',
            'Tyumen BatBear',
            'TYUMEN BATTERY',
            'U.S.Battery',
            'UkorAuto',
            'Ultimatum',
            'UNICORN',
            'Uniforce',
            'UNIKUM',
            'UPLUS',
            'URANIUM',
            'Urban',
            'VAG',
            'Vaiper',
            'Vapcell',
            'VARTA',
            'VEKTOR ENERGY',
            'Vela',
            'Ventura',
            'Verton',
            'Vesna',
            'VETER',
            'Vettler',
            'Vianor',
            'Virbac',
            'VISMAR',
            'VOIL',
            'VOLAT',
            'VOLKSWAGEN',
            'Volt',
            'Volteco',
            'Voltmaster',
            'Volton',
            'Volvo',
            'VORTEX',
            'VST',
            'WATTBATT',
            'Wattex',
            'Wattico',
            'WBR',
            'WESTA',
            'Wezer',
            'WPR',
            'WURTH',
            'X-FORCE',
            'X-treme',
            'XStream',
            'YAKUDZA',
            'YATO',
            'YELLOW',
            'YUASA',
            'ZAP',
            'ZDF',
            'Zeus',
            'ZIKMAR',
            'ZION',
            'Zlatek',
            'ZOTA',
            'Zubr',
            'Аrctic Batbear',
            'АВАР',
            'АвтоФан',
            'Аком',
            'АкТех',
            'Аляsка',
            'Атлант',
            'Атлантис Пласт',
            'АТОЛ',
            'БАСТИОН',
            'БелЗАН',
            'Болид',
            'БРТ',
            'ВОСТОК',
            'Восток Стиль',
            'ГАЗ',
            'Газпромнефть',
            'ГЛАВДОР',
            'ДИАЛУЧ',
            'Доброе дерево',
            'Зверь',
            'Зверьё Моё',
            'Золотая Клетка',
            'Зооник',
            'ИРКУТ',
            'Исток',
            'КАЗ',
            'Камаз',
            'КАМАЗавтотехника',
            'КАТЕКО Energy',
            'Катод',
            'Керамика ручной работы',
            'Книга по требованию (перепечатка)',
            'Курские аккумуляторы',
            'ЛУКОЙЛ',
            'МАСТАК',
            'МЕГЕОН',
            'МЕДВЕДЬ',
            'Мореман',
            'НЭТЕР',
            'Облик',
            'Омега',
            'ОРИОН',
            'Павловский автобусный завод',
            'Памир',
            'Парус электро',
            'Пижон',
            'Пижон Aqua',
            'Подольский аккумуляторный завод',
            'ПУЛЬС',
            'Ростов',
            'Рубин',
            'РУССКАЯ ЗВЕЗДА',
            'Сайбер Электро',
            'СОАТЭ',
            'СОЮЗ',
            'Татнефть',
            'Теплый пол №1',
            'ТЕРЕК',
            'ТРАКТ',
            'Тула',
            'Тюменский медведь',
            'УАЗ',
            'Уральская Аккумуляторная Компания',
            'Чистый котик',
            'ЭКСМО',
            'Электра',
            'Электроисточник',
            'Электротранспорт Тамбов',
            'Энергия',
            'Энкор',
            'Этель',
            'ЯМАЛ'
        },
        'lxwxh': {
            '113x38x85',
            '113x70x105',
            '113x70x130',
            '113x70x86',
            '114x70x85',
            '114x71x131',
            '120x62x129',
            '120x70x92',
            '133x90x164',
            '134x80x160',
            '134x89x164',
            '134x89x176',
            '135x75x138',
            '137x77x135',
            '148x88x180',
            '150x160x165',
            '150x66x93',
            '150x70x105',
            '150x70x130',
            '150x70x145',
            '150x87x105',
            '150x87x110',
            '150x87x130',
            '150x87x145',
            '150x87x147',
            '150x87x159',
            '150x87x161',
            '150x87x93',
            '150x87x94',
            '150x88x105',
            '150x88x110',
            '150x88x93',
            '151x34x94',
            '151x88x110',
            '160x90x160',
            '168x132x192',
            '175x100x175',
            '175x87x155',
            '175х175х190',
            '181x73x176',
            '187х127х227',
            '205x70x162',
            '205x87x162',
            '207х175х175',
            '207х175х190',
            '230х175х225',
            '232х173х190',
            '232х173х225',
            '232х175х225',
            '237х127х226',
            '238х129х225',
            '238х129х227',
            '242x175x175',
            '242х175х190',
            '260x175x220',
            '260х175х225',
            '261х175х220',
            '276x175x175',
            '276x175x190',
            '277х175х190',
            '278x175x190',
            '278х175х175',
            '278х175х190',
            '306x175x220',
            '306х173х225',
            '306х175х225',
            '315x175x175',
            '315x175x190',
            '315х175х175',
            '352х175х190',
            '353x175x175',
            '353x175x190',
            '353х175х175',
            '353х175х190',
            '390х175х190',
            '393x175x190',
            '394x175x190',
            '513x189x223',
            '513х223х223',
            '518x240x242',
            '518x276x242',
            '70x47x100'
        },
        'voltage': {'12', '24', '6'},
        'corpus_type': {
            'B19',
            'B24',
            'D23',
            'D26',
            'D31',
            'D33',
            'E41',
            'L1',
            'L2',
            'L3',
            'L4',
            'L5',
            'L6',
            'LB2',
            'LB3',
            'LB4',
            'LB5'
        },
    },
    'wheels': {
        'brand': {
            "100%",
            "1000 Miglia",
            "1AV",
            "3Dpoint",
            "4 Racing",
            "4Go",
            "57 MOTORSPORT",
            "885",
            "AC Schnitzer",
            "AC strong",
            "Accuride",
            "Ace",
            "ACE-Q",
            "ACEFAST",
            "Acer",
            "ACQ",
            "Acura",
            "ADDI",
            "Adora",
            "Advan",
            "Advanti",
            "ADVICS",
            "AERO",
            "Aero",
            "Aerocker",
            "AEZ",
            "AFFIX",
            "AGESTAR",
            "AGForged",
            "AITL",
            "Akita",
            "Alba",
            "ALCAR",
            "ALCAR",
            "ALCASTA",
            "Aleks",
            "Alessio",
            "Alex",
            "Alfa Romeo",
            "Allante",
            "Allied Nippon",
            "Allied Wheel",
            "Alltech",
            "Alster",
            "Altenzo",
            "Aluchrom",
            "Alutec",
            "Amati",
            "American Racing",
            "ANDROS",
            "Angel",
            "Antera",
            "Anzio Wheels",
            "Aoshima",
            "Apollo",
            "AQUA",
            "Arays",
            "Arbet",
            "Arbex",
            "Arcasting",
            "Arirang",
            "Arivo",
            "Army",
            "Arrivo",
            "Arrma",
            "Artec",
            "artFORM",
            "ArtNoMore",
            "AS METAL",
            "ASA",
            "ASAM",
            "Asanti",
            "ASC",
            "Asterro",
            "ASW",
            "AT",
            "ATE",
            "Atom Race",
            "ATP",
            "ATS",
            "ATS Exclusive Line",
            "AudioCodes",
            "August",
            "Austar",
            "Autec",
            "AUTO-GUR",
            "Autogreen",
            "Autom",
            "Autostyle",
            "Avant Garde",
            "Avarus",
            "AVENUE",
            "AVT",
            "AVUS",
            "AW",
            "AWS",
            "AXE",
            "Axxion",
            "AY",
            "AZ",
            "Azev",
            "Baccarat",
            "Ballistic",
            "BANTAJ",
            "Banzai",
            "Baosh",
            "Barclay",
            "BARRACUDA",
            "Barret",
            "BAW",
            "Bayer Garden",
            "BAZO",
            "BBS",
            "BELARUS",
            "Benalu",
            "Beral",
            "Berg",
            "Bestop",
            "BETTER",
            "Beyern",
            "BFGoodrich",
            "BHV",
            "Binno",
            "BK",
            "Black Rhino",
            "Blade",
            "BLAQUE DIAMOND",
            "Blue Fox",
            "BLUE PRINT",
            "BM-Motorsport",
            "BMW",
            "Bontyre",
            "BOOS",
            "Borbet",
            "BOSCH",
            "Bosch",
            "Brabus",
            "BRADEX",
            "BRAUBERG",
            "BRC",
            "brembo",
            "Breyton",
            "Bridgestone",
            "Brocard",
            "Brock",
            "Broomer",
            "BSA",
            "BSE",
            "BTS",
            "Buffalo",
            "Buick",
            "BWR",
            "BY",
            "BYD",
            "CAM",
            "Can Otomotiv",
            "Caractere",
            "Carbyne",
            "Carlsson",
            "Carmani",
            "Carre",
            "Carwel",
            "Carwell",
            "Cattivo",
            "Catwild",
            "CEC Wheels",
            "Centara",
            "Centillion",
            "CHANGAN",
            "Chaoyang",
            "CHERY",
            "CHEVROLET",
            "Chrysler",
            "CIDEB",
            "CITROEN",
            "CLE International",
            "Cloyes",
            "CMS",
            "CMST",
            "CNIC",
            "Color1",
            "Com4Wheels",
            "Comet",
            "Comfort",
            "Compomotive",
            "Continental",
            "Cordiant",
            "Corniche Sports Wheels",
            "Cosmis Racing Wheels",
            "Coventry",
            "COX",
            "Crista",
            "Cromodora",
            "Cross Street",
            "CroSSSport",
            "CW Fahrzeugtechnik",
            "CWORKS",
            "D&P",
            "DACIA",
            "Daewoo",
            "DAF",
            "DAIHATSU",
            "Datsun",
            "DBL-G",
            "DBV",
            "Decathlon",
            "Defy",
            "Delta DL",
            "delta4x4",
            "Deluxe Wheels",
            "Detata",
            "Devino",
            "DEZENT",
            "DHS",
            "Diablo Wheels",
            "DIAL",
            "DIAMO",
            "DIEWE",
            "Disla",
            "DJ WHEELS",
            "DLT",
            "Dodge",
            "DOLZ",
            "Dotz",
            "DP Group",
            "Dr. Schulze",
            "DreamCar Technology",
            "Drewske",
            "Driv",
            "Dropstars",
            "DT spare parts",
            "Dualtron",
            "DUB",
            "Dunlop",
            "Dupli-Color",
            "Duratrax",
            "DVINCI",
            "DWS",
            "Dynamo",
            "DZ EXKLUSIV",
            "Ecanto",
            "ECM Records",
            "ECO drive GEAR",
            "ECOPRO",
            "ED",
            "Edition Leipzig",
            "Editura Meridiane",
            "EKKA",
            "ELTRA",
            "Emotion Wheels",
            "Enfes",
            "Enkei",
            "Ensure",
            "Enzo",
            "Erisson",
            "ET",
            "Eta Beta",
            "Eurodisk",
            "EuroEx",
            "Eurorepar",
            "Evans",
            "Extreme Fishing",
            "F1",
            "Falken",
            "FAW",
            "FDF",
            "Febi",
            "Federal",
            "Fenox",
            "Ferodo",
            "Festool",
            "FIAT",
            "Firemax",
            "Fly",
            "Focal",
            "FoMoCo",
            "Fondmetal",
            "Foose",
            "For Wheels",
            "Ford",
            "Forge-Tec",
            "Forgiato",
            "Formula",
            "Forsage",
            "Forzza",
            "FOTON",
            "FR Design",
            "Freemotion",
            "Frenkit",
            "FSW",
            "FTK",
            "Fuel",
            "Fujibond",
            "Futek",
            "G-Max",
            "GAH ALBERTS",
            "Gallimard",
            "Geely",
            "GENERAL MOTORS",
            "Gianelle",
            "GIANNA",
            "Giant",
            "GIGANT",
            "Ginell",
            "Giovanna",
            "Gislaved",
            "GMP",
            "Gold Wheel",
            "Goodyear",
            "GR",
            "GRAM LIGHTS",
            "Granite Alloy",
            "Grenlander",
            "Grid",
            "GSI",
            "GT Radial",
            "GTMRK",
            "Guahoo",
            "Guardo",
            "Hachette Book Group",
            "Haida Group",
            "haima",
            "Hamann",
            "Hangcha",
            "Hankook Tire",
            "Harp",
            "Hartung",
            "Haval",
            "Hayes Lemmerz",
            "HD Wheels",
            "HDS",
            "Helo",
            "HI-LIFT",
            "HI-TECH",
            "Hidom",
            "Hilberg",
            "Himoto",
            "Hipnotic Wheels",
            "Honda",
            "HONG SUNG BRAKE",
            "Hosco",
            "Hot Wheels",
            "HP Design",
            "HPI",
            "HRE",
            "HTRC",
            "HUMMER",
            "Husqvarna",
            "HYUNDAI",
            "Hyundai/KIA",
            "iFree",
            "II Crave Alloys",
            "IJI",
            "IJITSU",
            "IKON ALLOY",
            "Inakustik",
            "Incubus",
            "Incurve Wheels",
            "Infiny",
            "Inforged",
            "Inter Action",
            "Intra-Exip",
            "Invader",
            "ION",
            "Irbis",
            "IST Models",
            "Isuzu",
            "ITP",
            "itWheels",
            "IVECO",
            "Ivision Wheels",
            "IWheelz",
            "J&L Racing",
            "JAC",
            "Jacob Delafon",
            "Jaguar",
            "Jantsa",
            "JCB",
            "JD",
            "Jeep",
            "Jenavi",
            "JETA PRO",
            "Jetson",
            "Jihoo",
            "JIKIU",
            "JMC",
            "JMC PARTS",
            "JT",
            "JTC AUTO TOOLS",
            "K&K",
            "K7",
            "Kagayaki",
            "Kahn",
            "KAISER",
            "Kapsen",
            "KAYO",
            "KDW",
            "KE",
            "Kelleners Sport",
            "KELLYS",
            "Keskin Tuning",
            "KFZ",
            "Khomen Wheels",
            "KIA",
            "KingStar",
            "Klein",
            "KMC",
            "Kocateq",
            "Koko Kuture",
            "Konig",
            "Kordell",
            "Kormetal",
            "Kormoran",
            "Kosei",
            "KRAFT",
            "Kronprinz",
            "KTM",
            "KUGOO",
            "KWM",
            "Kyowa Racing",
            "Kyvol",
            "L.A. Connection",
            "L.O.L.",
            "La Pinta",
            "LADA",
            "LAKE COUNTRY",
            "Lancia",
            "Land Rover",
            "Landsail",
            "Larex",
            "Lavka Games",
            "Lawu",
            "League",
            "LegeArtis",
            "Lenso",
            "Lexani",
            "LEXUS",
            "LF Works",
            "Lifan Motors",
            "Lincoln",
            "Ling Long",
            "Lipai",
            "LIVEUP",
            "LIZARDO",
            "LM",
            "LOEBRO",
            "Lorenso",
            "LORENZO",
            "LRG",
            "LS",
            "LS Flow Forming",
            "LS Forged",
            "LS Wheels",
            "Lumag",
            "Lumarai",
            "Lux",
            "Luyusitong",
            "LW",
            "M&K",
            "M1",
            "Magline",
            "Magma",
            "Magnetto Wheels",
            "Magnum",
            "MAJORSELL",
            "Mak",
            "MAK",
            "Makstton",
            "MALATA",
            "MAM",
            "Mamba",
            "MAN",
            "Mandrus",
            "Mangels",
            "Mannol",
            "MAPCO",
            "Marcello",
            "Maritima Ceramics",
            "Maserati",
            "Mashinokom",
            "MASUMA",
            "Matador",
            "Matrix",
            "MATUR UNTY",
            "Maxion",
            "MAXX Wheels",
            "MAXXIS",
            "Mayhem",
            "Mazda",
            "Mazzi",
            "MB Design",
            "Mefro",
            "Mega",
            "Megami",
            "MeisterWerk",
            "Menzari",
            "Mercedes-Benz",
            "Meritor",
            "Merloni",
            "Mersedes",
            "Metabo",
            "MetalPart",
            "Method",
            "MHT",
            "Mi-tech",
            "MICHELIN",
            "Mickey Thompson",
            "Mille Miglia",
            "Millenium",
            "MIM",
            "Min-Shian",
            "Minako",
            "MINI",
            "Mitsubishi",
            "Mitsuboshi",
            "MKW OFF-ROAD ",
            "MML",
            "modular",
            "Modular Society",
            "Momo",
            "Monte Fiore",
            "Moshi",
            "Motec",
            "Motegi Racing",
            "MotionLamps",
            "MOTO Metal",
            "MotoLand",
            "Motul",
            "MPW",
            "Mr. Painter",
            "MS Motorsports",
            "MST Wheels",
            "MSW",
            "Musea Records",
            "MWheels",
            "MZ",
            "N2O",
            "Nakayama",
            "NB Wheels",
            "NEO",
            "Neo Wheels",
            "Nexen",
            "Next",
            "NIBK",
            "Niche",
            "Niki",
            "Ningbo",
            "NingBo",
            "NINGBO MOTOR",
            "Nintendo",
            "Nissan",
            "NISSHINBO",
            "NO NAME",
            "Nokian Tyres",
            "Nologo",
            "Noname",
            "Nonesuch Records",
            "Nordway",
            "NORMAKS",
            "NorStone",
            "NP-Wheels",
            "NW Wheels",
            "NZ Wheels",
            "OE",
            "Oehlbach",
            "Oem",
            "OEM-Tuning",
            "OFF-ROAD Wheels",
            "Olaff",
            "ONE WAY",
            "ONYARBI",
            "Opel",
            "ORE",
            "Original series wheels",
            "ORW",
            "Oxigin",
            "OXXO",
            "OZ Racing",
            "P&W",
            "PANTHER",
            "PART ONE",
            "PATRON",
            "PDW Wheels",
            "PE Automotive",
            "Perri's",
            "Perricone MD",
            "PEUGEOT",
            "Pirelli",
            "PitBikeClub",
            "Platin",
            "Platinum",
            "PNB",
            "Polcar",
            "Police",
            "PONTIAC",
            "Popular",
            "PORSCHE",
            "Powcan",
            "Powertrac",
            "Pozis",
            "PRAVT",
            "Premium Series",
            "PRIMO",
            "Pro Comp",
            "PROCUT",
            "Proline Wheels",
            "Proma",
            "ProVia",
            "PS",
            "PSA Peugeot Citroen",
            "PTW",
            "Punto",
            "Queen Fair",
            "R-Steel",
            "R-TEX",
            "R-Zone",
            "Race Face",
            "Race Ready",
            "RACING",
            "Racing Sparco",
            "Racing Wheels",
            "Radius",
            "Rapid",
            "Rastar",
            "Rays",
            "RC Design",
            "RE:Style",
            "Reader's Digest",
            "Ready2Robot",
            "Reco",
            "Red Wheel",
            "Redbourne",
            "redBTR",
            "REDPOWER",
            "Regulmoto",
            "REline",
            "Remain",
            "Remo Hobby",
            "remove",
            "Renault",
            "RENAULT TRUCKS",
            "Renzo",
            "Replay",
            "Replica",
            "RepliKey",
            "Repriza",
            "RH Alurad",
            "RIAL",
            "RICHIESTO",
            "Ridler",
            "Riginal",
            "River Hobby",
            "Roadstone",
            "RoadX",
            "Romagna Ruote",
            "Ronal",
            "Rondell",
            "Roner",
            "ROSSO",
            "ROSSVIK",
            "Rostar",
            "Roxtone",
            "Royal Wheels",
            "RPLC-Wheels",
            "RS Wheels",
            "RST",
            "RUFF",
            "Runva",
            "RUSCH",
            "Rusconnect",
            "Russian Roulette A NEW LEVEL OF TAGGING",
            "Russtec",
            "Rutrike",
            "RW CLASSIC",
            "RZT",
            "S&K GmbH",
            "SAAB",
            "SAF Holland",
            "Sakura Wheels",
            "SAMPA",
            "Sanfox",
            "SANT",
            "SB Nagamochi",
            "SCANIA",
            "Schmidt",
            "SCORPENA",
            "SDLG",
            "SDT",
            "SEAT",
            "Sebring",
            "Secret Wheels",
            "Seiken",
            "Selective Professional",
            "SEYEN",
            "SH",
            "Shaper",
            "Shark",
            "Siberian Rivers World",
            "Sintez Records",
            "SITITEK",
            "SKAD",
            "SKILL",
            "Skillfaster",
            "Skoda",
            "SKYWER",
            "SL",
            "Slik",
            "SM",
            "Smart",
            "SmartBuy",
            "SMC",
            "SNOWMEN",
            "SNP",
            "Sodi Wheels",
            "Soleco",
            "SONATEX",
            "SONAX",
            "Sony",
            "Sparco Wheels",
            "Spath",
            "Speedline Corse",
            "Speeds",
            "Sportmax Racing",
            "SportWay",
            "Sprinter",
            "SRD Tuning",
            "SsangYong",
            "SSC",
            "SSW",
            "Staler",
            "Stalker",
            "Stark",
            "starke",
            "Staro",
            "Start Line",
            "Startec",
            "STD",
            "Steel Wheels",
            "Steger",
            "Stellox",
            "Stilauto",
            "Stonewell",
            "Storm Wheels",
            "Stretch",
            "Strut",
            "Styl",
            "SUBARU",
            "Sunfull",
            "Sunrise",
            "SUNTOUR",
            "SuperMetal",
            "SUPERWINCH",
            "SUPRA",
            "SUZUKI",
            "SW",
            "SWAT",
            "Swiger",
            "Sword",
            "Swortech",
            "Symposium",
            "T-max",
            "Tailong",
            "Tamiya",
            "Tansy wheels",
            "TANTOS",
            "TAYGA",
            "TCIC",
            "Team Dynamics",
            "TEC Speedwheels",
            "Tech-Line",
            "Tecnomagnesio",
            "TEROSON",
            "Tevako",
            "Textar",
            "Tezzen",
            "TGR",
            "TGRACING",
            "The Noble Collection",
            "Tigar",
            "TIS",
            "TLC",
            "TLtriumph",
            "TMMP",
            "Tomason",
            "Toora",
            "Top Driver",
            "Torque",
            "Toyo",
            "TOYOTA",
            "TR Design",
            "Tracmax",
            "Transmaster",
            "Trebl",
            "Triangle Group",
            "Tribuna",
            "TRIXIE",
            "TRW",
            "Tsn",
            "TSR",
            "TSW",
            "Tunga",
            "Tunzzo",
            "TURTEL",
            "Tutela",
            "TWG",
            "TYC",
            "U.S. Wheel",
            "Ultra Wheel",
            "Ultra Wheels",
            "Uncle Milton",
            "Urban Racing",
            "VAG",
            "Valbrem",
            "Valente",
            "Valeo",
            "Vault",
            "VCT",
            "Vebex",
            "Veloche",
            "Venti",
            "Verde",
            "Verlag Enzyklopadie",
            "Vertex",
            "Vertini",
            "VIA",
            "VIAIR",
            "Vianor",
            "Viatti",
            "Victor Equipment",
            "Vindeta",
            "Viscera",
            "Vissol",
            "VMR Wheels",
            "VOLK RACING",
            "VOLKSWAGEN",
            "Volvo",
            "Vorsh",
            "Vorxtec",
            "Vossen",
            "Wabco",
            "WALD",
            "Walpax",
            "Warner Bros.",
            "Westlake Tyres",
            "Wheels UP",
            "Wheelworld",
            "WIEDERKRAFT",
            "Wiger",
            "WM",
            "WOLF Wheels",
            "Work",
            "WRC",
            "WSP Italy",
            "X'trike",
            "X-Line",
            "X-Race",
            "X7",
            "XD Series",
            "Xinfa",
            "XLine",
            "XO Luxury",
            "Xtra Wheels",
            "XXIO",
            "XXR Wheels",
            "Yamaha",
            "Yamato",
            "Yido",
            "Yokatta",
            "Yokatta Rays",
            "Yokohama",
            "Yokomo",
            "YST",
            "YUEJIN",
            "Yueling wheels",
            "Yuki",
            "Z-Performance",
            "ZD WHEELS",
            "Zeetex",
            "Zent",
            "Zepp",
            "ZEUS-WHEELS",
            "Zinik",
            "Zippo",
            "Zorat Wheels",
            "Zormer",
            "ZRacing",
            "Zumbo Wheels",
            "Аванта (АСТ)",
            "Автомагнат",
            "АВТОПИЛОТ",
            "АвтоРеал",
            "АВТОСПАС",
            "Автотехнология",
            "Азбука",
            "Азбука-Классика",
            "Академия гуманитарных исследований",
            "Академия наук СССР",
            "Алетейя",
            "Алмазный инструмент",
            "Альта-Принт",
            "Альфа-книга",
            "Амрита-Русь",
            "Аркаим",
            "АСТ",
            "Атака",
            "Атомиздат",
            "Белагрохимторг",
            "Беларус",
            "БелЗАН",
            "Библиополис",
            "Вага",
            "Вагриус",
            "ВАЗ",
            "Вектор",
            "Верхняя Волга",
            "Весь",
            "Вече",
            "ВИКОМ",
            "ВИМ КАБЕЛЬ",
            "Владис",
            "Внешторгиздат",
            "Воениздат",
            "Всероссийское театральное общество",
            "ВСМПО",
            "Вся Москва",
            "Высшая школа",
            "Вышэйшая школа",
            "ГАЗ",
            "Галерия",
            "Гардарика",
            "Географгиз",
            "Герои Отечества",
            "Гидрометеоиздат",
            "ГИОРД",
            "ГЛАВДОР",
            "Голос",
            "Гранд-Фаир",
            "ДАЛИ-авто",
            "ДЕАН",
            "Детская литература",
            "Детская литература. Ленинград",
            "ДОСААФ",
            "Западно-Сибирское книжное издательство",
            "Запорожский Автомобилестроительный Завод",
            "Инновационное машиностроение",
            "ИнтерДайджест",
            "Искусство",
            "Искусство России",
            "КАМА",
            "КАМАЗавтотехника",
            "Канон",
            "Клуб семейного досуга",
            "Книга",
            "Книга по требованию (перепечатка)",
            "Книжный мир",
            "КноРус",
            "Коло",
            "Коммерсантъ",
            "Комсомольская правда",
            "КраМЗ",
            "Краснодарское книжное издательство",
            "Кременчугский колёсный завод",
            "Крон-Пресс",
            "Крылов",
            "КУЛЗ",
            "Культ-информ-пресс",
            "КУМЗ",
            "Курские аккумуляторы",
            "Кэдмэн",
            "УАЗ",
            "Ё-wheels"
        },
        'diam': {
            "10",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "17.5",
            "18",
            "19",
            "19.5",
            "20",
            "21",
            "22",
            "22.5",
            "23",
            "24",
            "25",
            "26",
            "28"
        },
        'bolts_diam': {
            "100",
            "105",
            "108",
            "110",
            "112",
            "114",
            "114.3",
            "115",
            "118",
            "120",
            "120.6",
            "120.65",
            "120.7",
            "122",
            "125",
            "127",
            "130",
            "132",
            "135",
            "139",
            "139.1",
            "139.7",
            "150",
            "160",
            "165",
            "165.1",
            "170",
            "175",
            "180",
            "190",
            "199",
            "200",
            "203.2",
            "205",
            "208",
            "210",
            "220",
            "222.25",
            "222.5",
            "225",
            "232",
            "245",
            "250",
            "256",
            "275",
            "285",
            "285.75",
            "286",
            "335",
            "415",
            "425",
            "450",
            "505",
            "98"
        },
        'bolts': {
            "1",
            "10",
            "12",
            "20",
            "3",
            "4",
            "5",
            "6",
            "8",
            "9"
        },
        'width': {
            "10",
            "10.25",
            "10.5",
            "10.75",
            "11",
            "11.25",
            "11.5",
            "11.75",
            "12",
            "12.5",
            "13",
            "14",
            "15",
            "16",
            "17",
            "19.5",
            "3",
            "3.5",
            "4",
            "4.5",
            "5",
            "5.25",
            "5.5",
            "6",
            "6.5",
            "6.75",
            "7",
            "7.25",
            "7.5",
            "8",
            "8.25",
            "8.5",
            "8.75",
            "9",
            "9.5",
            "9.75",
            "9.9"
        }
    },
    'tires': {
        'brand': {
            "2XU",
            "ABB",
            "Accelera",
            "ACG",
            "Achilles",
            "ACQ",
            "ADDO",
            "Aderenza",
            "Advance",
            "AE&T",
            "Aeolus",
            "AeroCool",
            "Agoform",
            "AIRLINE",
            "ajusa",
            "Alfa Romeo",
            "All Balls",
            "Alliance Tire Group",
            "ALLVEGA",
            "Almighty Eagle",
            "Altenzo",
            "Amberstone",
            "AMD",
            "America",
            "AMP",
            "AMT Electronics",
            "Amtel",
            "Anjie",
            "ANLAS",
            "Annaite",
            "Antares",
            "Aosen",
            "Aoshima",
            "Aoteli",
            "APLUS",
            "Apollo tyres",
            "Aptany",
            "Arctic Claw",
            "Ardecoled",
            "Areol",
            "Arirang",
            "Arisun",
            "Arivo",
            "Arktic",
            "Arlight",
            "Armour",
            "Artum",
            "AS METAL",
            "ASAM",
            "ASPACO",
            "ATLANDER",
            "Atlas",
            "ATLASBX",
            "Atturo",
            "Aufine",
            "Auplus Tire",
            "Aurora Tire",
            "Austone",
            "Austyre",
            "Autobacs",
            "Autogreen",
            "Autogrip",
            "Autoguard",
            "AUTOPROFI",
            "Avatyre",
            "AVMazzega",
            "AVON",
            "AVS",
            "Barkley",
            "BARS",
            "Barum",
            "BCT",
            "Bearway",
            "BENDIX",
            "Berga",
            "Bestrich",
            "Bestway",
            "BFGoodrich",
            "Bianchi",
            "Big O Tires",
            "Biolatic",
            "BioNelia",
            "BKT",
            "Black-Star",
            "Blacklion",
            "Blackstone",
            "BMW",
            "Bontyre",
            "Bornsoon",
            "BOSCH",
            "Boto",
            "Brasa",
            "Bridgestone",
            "Briway",
            "Btrace",
            "Bud",
            "Bullong Tyre",
            "BYD",
            "Cachland",
            "CAMAC",
            "Camoplast Solideal",
            "Capitol",
            "CARGO",
            "Carps",
            "CEAT",
            "Centara",
            "CFMOTO",
            "Chaoyang",
            "Chengshan",
            "CHEVROLET",
            "Chrysler",
            "CITROEN",
            "Clear",
            "Clear Line",
            "Clipper",
            "Comforser",
            "Comfort",
            "Compasal",
            "Constancy",
            "Continental",
            "Contyre",
            "Cooper",
            "Cordiant",
            "Cordovan",
            "CR",
            "Cratos",
            "Cross Street",
            "Crossleader",
            "CST",
            "Cultor",
            "DACIA",
            "Daewoo",
            "DAF",
            "Dahua",
            "DAIHATSU",
            "Davanti",
            "Dayton",
            "Dean Tires",
            "Debica",
            "Deestone",
            "DELINTE",
            "Delmax",
            "Demar",
            "Deruibo",
            "Dessert Fantasy",
            "Dextero",
            "Diamondback",
            "Dick Cepek",
            "Diplomat",
            "DMACK",
            "Dodge",
            "Double Coin",
            "Double Eagle",
            "DoubleStar",
            "Ducati",
            "Dunlop",
            "Dunlop Home Products",
            "Duran",
            "Duraturn",
            "Durun",
            "Dynamo",
            "E-MODE",
            "EcoOpony",
            "ECOPRO",
            "ECOTEX",
            "Effiplus",
            "Eldorado Tire",
            "ELITECH",
            "Enfes",
            "EP Tyres",
            "ERREVI",
            "ESA-Tecar",
            "ESSO",
            "Eurorepar",
            "Eurotec",
            "Event",
            "Evergreen",
            "Falken",
            "Faralong",
            "FARROAD",
            "FAST",
            "Fast",
            "Fate",
            "FEBEST",
            "Federal",
            "Fedima",
            "Fenix",
            "Fenox",
            "Festool",
            "FIAT",
            "Firemax",
            "Firestone",
            "FirstStop",
            "Foam Heroes",
            "Force",
            "Forceum",
            "Ford",
            "Forerunner",
            "Formula",
            "Fortio",
            "Fortuna",
            "Fortune",
            "FORWARD",
            "Forward",
            "Fronway",
            "Fulda",
            "Fullrun",
            "Fullway",
            "Fuzion",
            "G-Energy",
            "Galaxy",
            "GARSING",
            "Geely",
            "GENERAL MOTORS",
            "General Tire",
            "Gerutti",
            "Giant",
            "Ginell",
            "Gislaved",
            "Giti",
            "GlobalTOOLS",
            "Gloria Vanderbilt",
            "Goalstar",
            "Goform",
            "Gold Star",
            "Goldline",
            "Goldway",
            "Goodfriend",
            "Goodride",
            "Goodtyre",
            "Goodyear",
            "Gran-Stone",
            "Green Dragon",
            "GreenDiamond",
            "Greenlander",
            "GREENTRAC",
            "Gremax",
            "Grenlander",
            "GripMax",
            "GT Radial",
            "Guardo",
            "Habilead",
            "Haida Group",
            "Hankook Tire",
            "Headway",
            "Heidenau",
            "Hemisphere",
            "Hercules",
            "Herovic",
            "Hifly",
            "High Performance",
            "Hilo",
            "HINO",
            "Honda",
            "Horizon",
            "HPI",
            "Husqvarna",
            "Huter",
            "HYUNDAI",
            "Hyundai/KIA",
            "IDEAL LUX",
            "IDEMITSU",
            "Idilis",
            "Ikon",
            "Ikon Tyres",
            "iLINK",
            "ILTANI",
            "Imperial",
            "Infinity Tyres",
            "Ink Machines",
            "INNOMOUNT",
            "Insa Turbo",
            "Interco",
            "Interstate",
            "Intertrac",
            "Invovic",
            "IQ-ZABIAKA",
            "iQZiP",
            "Ironman",
            "Iseto",
            "ist",
            "IVECO",
            "JAKO",
            "Jeep",
            "Jetzon Tire",
            "Jinyu",
            "Journey",
            "Joyroad",
            "K&K",
            "Kapous",
            "Kapsen",
            "Kebek",
            "Kelly",
            "Kenda",
            "Kenex",
            "Keter",
            "Khomen Wheels",
            "Kinforest",
            "King Meiler",
            "Kingrun",
            "Kings Tire",
            "KingStar",
            "KingStone",
            "Kleber",
            "Kormoran",
            "Kpatos",
            "KRAFT",
            "KTM",
            "KUGOO",
            "Kumho",
            "Kustone",
            "LADA",
            "LAKESEA",
            "Land Rover",
            "lande",
            "Landsail",
            "Landspider",
            "Lanikai",
            "Lanvigator",
            "Lassa",
            "Laufenn",
            "Leao",
            "Lee Cooper",
            "LegeArtis",
            "Lexani",
            "LEXUS",
            "Lifan Motors",
            "Ling Long",
            "LingLong",
            "Lionhart",
            "Long March",
            "LotsPrints",
            "Luccini",
            "Luxxan",
            "LUZAR",
            "Mabor",
            "Magnum",
            "MAHLE",
            "Malatesta",
            "Maloya",
            "MAN",
            "Mannol",
            "Marangoni",
            "Marshal",
            "Massimo",
            "Mastercraft",
            "Mastersteel",
            "Matador",
            "Maxtrek",
            "MAXXIS",
            "Mayrun",
            "Mazda",
            "MAZZINI",
            "Medeo",
            "Membat",
            "Mentor",
            "Mercedes-Benz",
            "Meteor",
            "Metzeler",
            "MICHELIN",
            "Mickey Thompson",
            "Mileking",
            "Milestone",
            "Minerva",
            "MINI",
            "Mirage",
            "Mitas",
            "Mitsubishi",
            "MolyGreen",
            "Momo",
            "Motomaster",
            "MOTRIO",
            "Multi-Mile",
            "NAMA",
            "Nankang",
            "National",
            "Navigator",
            "Nereus",
            "Nerf Dog",
            "Neuton",
            "Nexen",
            "Nissan",
            "Nitto",
            "Nokia",
            "Nokian Tyres",
            "Noname",
            "Norauto",
            "Nordexx",
            "NORDFROST",
            "Nordman",
            "NORTEC",
            "Nortenha",
            "Novex",
            "OBOR",
            "Odyking",
            "OMSKSHINA",
            "ONYX Tires",
            "Opel",
            "Original",
            "Orium",
            "Ornet",
            "Otani",
            "Ovation Tyres",
            "Ozka",
            "PACE",
            "Parnelli Jones",
            "PasForm",
            "Paxaro",
            "PENTACON",
            "Perfect",
            "Petlas",
            "PEUGEOT",
            "Pirelli",
            "Pirelli Pzero",
            "Pitbull",
            "Platin",
            "PNEU VRANIK",
            "Pneumant",
            "Point S",
            "PolarStar",
            "PORSCHE",
            "Powertrac",
            "Premada",
            "Premiorri",
            "PRESA",
            "President",
            "Primewell",
            "Pro Comp",
            "PROFIL",
            "PSV",
            "Quattro Freni",
            "Racealone",
            "Radar tyres",
            "Radial",
            "Rapid",
            "RBI",
            "Regal",
            "Remington",
            "Renault",
            "RepliKey",
            "Rhino Rescue",
            "Riderover",
            "Riken",
            "Roadclaw",
            "Roadcruza",
            "ROADGUIDER",
            "ROADHIKER",
            "Roadking",
            "Roadlux",
            "Roadmarch",
            "ROADMAX",
            "Roadshine",
            "Roadstone",
            "RoadX",
            "Rockstone",
            "ROLF",
            "Rosava",
            "ROSSVIK",
            "Rotalla",
            "Rotex",
            "Routeway",
            "Rovelo",
            "Roxtone",
            "Roy Benson",
            "Royal Black",
            "RST",
            "RUGRAM",
            "Ruifulai",
            "Runway",
            "SAAB",
            "Saetta",
            "Saferich",
            "Saffiro",
            "Sagitar",
            "Sailun",
            "SAMAMA",
            "Satoya",
            "Sava",
            "SAVAGE&HERBS",
            "Schwalbe",
            "SDS EXCLUSIVE",
            "SEAT",
            "Sebring",
            "Seiberling",
            "Semperit",
            "Sigma",
            "Signet",
            "Silverstone",
            "Sime Tyres",
            "Simex",
            "SINTEC",
            "SKAD",
            "Skoda",
            "Sokany",
            "Sonar",
            "Sonny",
            "Sport",
            "Sport&Fun",
            "Sportiva",
            "SPORTRAK",
            "SsangYong",
            "Starco",
            "Starfire",
            "Starmaxx",
            "Starperformer",
            "Status",
            "Stellox",
            "STELS",
            "Stinger",
            "STINGER",
            "Strial",
            "Stunner",
            "SUBARU",
            "Sumitomo",
            "Sumo",
            "Sunew",
            "Sunfull",
            "Sunitrac",
            "SUNNY",
            "SUNTEK",
            "Sunwide",
            "Superguider",
            "Superia tires",
            "SWAG",
            "Syron",
            "T-Tyre",
            "Taitong",
            "Targum",
            "TATSUMI",
            "Taurus",
            "TECAR",
            "Techking",
            "Technic",
            "Telstar Tire",
            "tempra",
            "Terraking",
            "Three-A",
            "Thunderer",
            "Tianfu",
            "Tigar",
            "TIGARBO",
            "TMMP",
            "Toledo",
            "Tomket",
            "TORERO",
            "Torque",
            "TORQUE",
            "Toryo",
            "TOUGH",
            "Tourador",
            "Toyo",
            "TOYOTA",
            "Tracmax",
            "Transmaster",
            "Traxxas",
            "Trayal",
            "Trazano",
            "Trebl",
            "Trelleborg",
            "Tri Ace",
            "TRIANGL",
            "triangle",
            "Triangle Group",
            "Tristar",
            "TRUCKER",
            "Tunga",
            "Tyfoon",
            "Tyrex",
            "Unico Metall",
            "Uniglory",
            "Unigrip",
            "Uniroyal",
            "Usborne",
            "VAG",
            "Valleystone",
            "Valsa",
            "Vee Rubber",
            "Venezia",
            "Viatti",
            "Victar",
            "Victorun",
            "Viking",
            "Vitour",
            "Vittos",
            "VOLKSWAGEN",
            "Volvo",
            "Voyager",
            "Vredestein",
            "VSP",
            "Wai",
            "Wanli",
            "Warrior",
            "WARRIOR",
            "Waterfall",
            "Weeksai",
            "Welt",
            "Westlake Tyres",
            "Wheels UP",
            "Wideway",
            "Winda",
            "Windforce",
            "Windpower",
            "Winrun",
            "Winter Tact",
            "Wolfsburg",
            "WolfTyres",
            "WONDERLAND",
            "WTB",
            "X'trike",
            "Xiaomi",
            "XONIX",
            "YANSON",
            "Yatai",
            "Yatone",
            "Yeada",
            "YED",
            "Yokohama",
            "Your Way",
            "Z Tyre",
            "Zanier",
            "Zeetex",
            "Zen",
            "ZESTINO",
            "ZETA",
            "Zetum",
            "ZMAX",
            "АВТОПИЛОТ",
            "Аквалиния",
            "Алтайшина",
            "Аргус-Спектр",
            "Арсенал",
            "Барнаульский шинный завод",
            "БелРеаХим",
            "Белшина",
            "БХЗ",
            "Волтайр",
            "ВШЗ",
            "ГАЗ",
            "Гепоглос",
            "Днепрошина",
            "КАМА",
            "Кировский завод по обработке цветных металлов",
            "Книга по требованию (перепечатка)",
            "КОЛЕСНИК",
            "КШЗ",
            "ЛЕНАНД",
            "Магазин МедТехника",
            "Мастер-Спорт",
            "Медплант",
            "Мобил К",
            "МШЗ",
            "Нобель Пресс",
            "Петрошина",
            "Ремшип",
            "РОСМЭН",
            "Русский стиль",
            "Советский писатель. Москва",
            "Стиль Жизни",
            "Страна ЗОЖиЯ",
            "Татнефть",
            "ТЕКОМ",
            "ТЕХНОПАРК",
            "Тонировка Тебе",
            "Уралшина",
            "Феникс",
            "Феникс-Премьер",
            "ЭКСМО",
            "ЯШЗ"
        },
        'height': {
            "105",
            "25",
            "30",
            "35",
            "40",
            "45",
            "50",
            "55",
            "60",
            "65",
            "70",
            "75",
            "80",
            "85",
            "90",
            "95"
        },
        'diam': {
            "R12",
            "R13",
            "R14",
            "R15",
            "R16",
            "R16.5",
            "R17",
            "R18",
            "R19",
            "R20",
            "R21",
            "R22",
            "R22.5",
            "R23",
            "R24",
            "R25",
            "R26",
            "R27",
            "R28",
            "R29",
            "R30"
        },
        'width-prof': {
            "125",
            "135",
            "145",
            "155",
            "165",
            "175",
            "185",
            "195",
            "205",
            "215",
            "225",
            "235",
            "240",
            "245",
            "255",
            "265",
            "275",
            "285",
            "295",
            "305",
            "315",
            "325",
            "335",
            "345",
            "355",
            "365",
            "375",
            "385",
            "395",
            "405",
            "455"
        },
    }
}

yam_params_names_for_check = {
    'tires': ('height', 'diam', 'width-prof'),
    'wheels':  ('diam', 'bolts_diam', 'bolts', 'width'),
    'akk': ('lxwxh', 'voltage')
}

